# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/custom/clion-2019.3.5/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /usr/local/custom/clion-2019.3.5/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/newe/CLionProjects/acnl-player

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/newe/CLionProjects/acnl-player

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/custom/clion-2019.3.5/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/custom/clion-2019.3.5/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/newe/CLionProjects/acnl-player/CMakeFiles /home/newe/CLionProjects/acnl-player/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/newe/CLionProjects/acnl-player/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named acnl_player

# Build rule for target.
acnl_player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 acnl_player
.PHONY : acnl_player

# fast build rule for target.
acnl_player/fast:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/build
.PHONY : acnl_player/fast

src/audioPlayer.o: src/audioPlayer.cpp.o

.PHONY : src/audioPlayer.o

# target to build an object file
src/audioPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/audioPlayer.cpp.o
.PHONY : src/audioPlayer.cpp.o

src/audioPlayer.i: src/audioPlayer.cpp.i

.PHONY : src/audioPlayer.i

# target to preprocess a source file
src/audioPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/audioPlayer.cpp.i
.PHONY : src/audioPlayer.cpp.i

src/audioPlayer.s: src/audioPlayer.cpp.s

.PHONY : src/audioPlayer.s

# target to generate assembly for a file
src/audioPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/audioPlayer.cpp.s
.PHONY : src/audioPlayer.cpp.s

src/fileManager.o: src/fileManager.cpp.o

.PHONY : src/fileManager.o

# target to build an object file
src/fileManager.cpp.o:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/fileManager.cpp.o
.PHONY : src/fileManager.cpp.o

src/fileManager.i: src/fileManager.cpp.i

.PHONY : src/fileManager.i

# target to preprocess a source file
src/fileManager.cpp.i:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/fileManager.cpp.i
.PHONY : src/fileManager.cpp.i

src/fileManager.s: src/fileManager.cpp.s

.PHONY : src/fileManager.s

# target to generate assembly for a file
src/fileManager.cpp.s:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/fileManager.cpp.s
.PHONY : src/fileManager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/acnl_player.dir/build.make CMakeFiles/acnl_player.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... acnl_player"
	@echo "... edit_cache"
	@echo "... src/audioPlayer.o"
	@echo "... src/audioPlayer.i"
	@echo "... src/audioPlayer.s"
	@echo "... src/fileManager.o"
	@echo "... src/fileManager.i"
	@echo "... src/fileManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

